runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /update
  script: unused
  login: optional
  secure: optional
- url: /read
  script: unused
  login: optional
  secure: optional
- url: /list
  script: unused
  login: optional
  secure: optional
- url: /delete
  script: unused
  login: optional
  secure: optional
- url: /create
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
